[package]
name = "habit_hero_shared_tests"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
axum.workspace = true
http-body-util.workspace = true
serde_json.workspace = true
tower.workspace = true
